name: "Release Health Check"

on: 
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  healthcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: AWS Server Health Check
        uses: jtalk/url-health-check-action@v3
        with: 
          url: ${{ secrets.RELEASE_URI }}
          max-attempts: 3
          retry-delay: 1s
          
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Health-Check
          fields: repo, message, commit, action, eventName, ref, workflow, job, took
          github_token: ${{ secrets.ACCESS_TOKEN_GIT }}

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
